# Use Node.js base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and lock files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire app into the container
COPY . .

# Expose the default development port
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"]

# docker build -t portfolio-app-dev -f Dockerfile.dev .
# docker run -p 3000:3000 portfolio-app-dev
