services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=production
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
